spring.application.name=SmartRailApplication

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/smartrail
spring.datasource.username=root
spring.datasource.password=railApplicationDB
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto settings: 
# 'update' is fine for development, but use 'none' or 'validate' in production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true